import image from "../assets/no-image-placeholder.webp";

export interface house {
  houseNumber: number;
  description: string;
  curfew: boolean;
  price: number;
  distance: string;
  services: string[];
  backgroundImage: string;
  images: any[];
  location: string;
  [key:string]: any
}

const houses: house[] = [
  {
    houseNumber: 0,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 200,
    distance: "5km",
    images: [image, image, image, image],
    location: "Tynwald",
  },
  {
    houseNumber: 1,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 200,
    distance: "5km",
    images: [image, image, image, image],
    location: "Borrowdale",
  },
  {
    houseNumber: 2,
    description: "lorem ipsum",
    curfew: false,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 100,
    distance: "5km",
    images: [image, image, image, image],
    location: "Masasa Park",
  },
  {
    houseNumber: 3,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 150,
    distance: "5km",
    images: [image, image, image, image],
    location: "Chitungwiza",
  },
  {
    houseNumber: 4,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 568,
    distance: "5km",
    images: [image, image, image, image],
    location: "Tynwald",
  },
  {
    houseNumber: 5,
    description: "lorem ipsum",
    curfew: false,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 26,
    distance: "5km",
    images: [image, image, image, image],
    location: "Highfields",
  },
  {
    houseNumber: 6,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 290,
    distance: "5km",
    images: [image, image, image, image],
    location: "Borrowdale",
  },
  {
    houseNumber: 7,
    description: "lorem ipsum",
    curfew: false,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 150,
    distance: "5km",
    images: [image, image, image, image],
    location: "Masasa Park",
  },
  {
    houseNumber: 8,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Maboureign",
  },
  {
    houseNumber: 9,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Chitungwiza",
  },
  {
    houseNumber: 10,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Borrowdale",
  },
  {
    houseNumber: 11,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Glenview",
  },
  {
    houseNumber: 12,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Belvedere",
  },
  {
    houseNumber: 13,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Vainona",
  },
  {
    houseNumber: 14,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Masasa Park",
  },
  {
    houseNumber: 15,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Maboureign",
  },
  {
    houseNumber: 16,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Borrowdale",
  },
  {
    houseNumber: 17,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Mount Pleasant",
  },
  {
    houseNumber: 18,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Maboureign",
  },
  {
    houseNumber: 19,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Maboureign",
  },
  {
    houseNumber: 20,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Tynwald",
  },
  {
    houseNumber: 21,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Mount Pleasant",
  },
  {
    houseNumber: 22,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Highfields",
  },
  {
    houseNumber: 23,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Glenview",
  },
  {
    houseNumber: 24,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Tynwald",
  },
  {
    houseNumber: 25,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Belvedere",
  },
  {
    houseNumber: 26,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Mount Pleasant",
  },
  {
    houseNumber: 27,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Mount Pleasant",
  },
  {
    houseNumber: 28,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Vainona",
  },
  {
    houseNumber: 29,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Borrowdale",
  },
  {
    houseNumber: 30,
    description: "lorem ipsum",
    curfew: true,
    backgroundImage: "",
    services: ["lorem ipsum"],
    price: 305,
    distance: "5km",
    images: [image, image, image, image],
    location: "Tynwald",
  },
];

export const getHouses = () => {
  return houses;
};
